name: Publish package to GitHub Packages

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  pipeline:
    uses: "./.github/workflows/pipeline.yml"
  publish:
    runs-on: ubuntu-latest
    needs: [pipeline]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4
      - name: Publish package
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
